---
name: libs/langchain-experimental Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - 'libs/experimental/pyproject.toml'

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    with:
      working-directory: libs/experimental
    secrets: inherit