---
name: libs/langchain Release

on:
  push:
    branches:
      - master
    paths:
      - 'libs/langchain/pyproject.toml'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  release:
    uses:
      ./.github/workflows/_release.yml
    with:
      working-directory: libs/langchain
    secrets: inherit
