# Run unit tests with all optional packages installed.
name: test_all

on:
  push:
    branches: [master]
  pull_request:

env:
  POETRY_VERSION: "1.4.2"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: "1.4.2"
          cache-key: "extended"
          install-command: "poetry install -E extended_testing"
      - name: Run unit tests
        run: |
          make test
